export const MODULE_ACTION_INCREASEMENT = "MODULE_ACTION_INCREASEMENT"
export const MODULE_ACTION_REVERSE = "MODULE_ACTION_REVERSE"
export const MODULE_2_ACTION_INCREASEMENT = "MODULE_2_ACTION_INCREASEMENT"
export const MODULE_2_ACTION_REVERSE = "MODULE_2_ACTION_REVERSE"
